In [49]:
import pandas as pd
import surprise
import numpy as np

In [50]:
conbined_data1 = pd.read_csv('data/combined_data_1.txt')

print(conbined_data1.head())

print(conbined_data1.shape)

                     1:
1488844 3.0  2005-09-06
822109  5.0  2005-05-13
885013  4.0  2005-10-19
30878   4.0  2005-12-26
823519  3.0  2004-05-03
(24058262, 1)


In [47]:
#데이터 구성은 user_id , rating, timestamp로 구성되어 있습니다.

In [48]:
import os.path
import csv

list = []
movie_code = 0
search = ":"

with open('data/combined_data_1.txt','r') as textfile:
    for row in textfile:
        row_split = row.split()
        for element in row_split:
            element_split = element.split(',')
            check = element_split[0]
            result = check.find(search)
            check = check.replace(":","")
            if result == -1:
                element_split.append(movie_code)
                list.append(element_split)
            else:
                movie_code = check

KeyboardInterrupt: 

combined_data_1.txt 데이터가 

movie code:
    
    user_id , rating, timestamp 순으로 되어있어서 

user_id , rating, timestamp, movie code 순으로 배열을 만들었습니다.

In [ ]:
import csv

csvfile = open("C:/Users/Minwook/Documents/Netflix_data/data/test.csv","w",newline="")

csvwriter = csv.writer(csvfile)
for row in list:
    csvwriter.writerow(row)

csvfile.close()

데이터 구성은 각 영화에 해당되는 태그 마다 
user_id , rating, timestamp, movie code로 구성되어 있습니다.

Neflix data가 너무 큰 관계로 범위를 한정시켰습니다.
Neflix data가 user_id , rating, timestamp, movie code오 이루어진 textfile이 4개로
나누어져 있는데, 그 중에서 combined_data_1.txt 중 10명의 유저에 대한 Similarity를
구현해보았습니다. 수업을 들으면서 더 많은 양의 데이터를 처리할 수 있도록 노력하겠습니다!

In [51]:
import openpyxl
 
# 엑셀파일 열기
workbook = openpyxl.load_workbook('data/combined_data_1_part.xlsx')
 
# 현재 Active Sheet 얻기
workbook_value = workbook.active
element = [] 
list = []

for r in workbook_value.rows:
    user_id = r[0].value   # 행 인덱스
    rating = r[1].value
    timestamp = r[2].value
    movie_code = r[3].value
    
    element = element + [user_id, rating , movie_code] 
    list.append(element)
    element = []
# csv 파일을 불러드려서 User_id, rating, movie_code 순으로 되있는 리스트를 원소로 
# 갖는 리스트를 생성했습니다.
del list[0] 
# 처음 원소인 제목부분은 지웁니다.
print(list)

[[1488844, 3, 1], [2442, 3, 1], [915, 5, 1], [1333, 4, 3], [967, 1, 4], [685, 3, 5], [1488844, 4, 8], [1333, 3, 8], [2133, 2, 8], [695, 1, 8], [3292, 4, 8], [1856, 5, 8], [1488844, 2, 17], [2133, 2, 17], [1333, 4, 18], [1333, 3, 26], [1333, 2, 28], [2133, 3, 28], [1488844, 3, 30], [2442, 3, 30], [1333, 3, 30], [2133, 3, 30], [3292, 4, 30], [1856, 5, 30], [1488844, 3, 44], [1333, 3, 44], [2133, 3, 48], [1333, 3, 52], [3292, 4, 52], [1333, 2, 55], [1333, 4, 57], [1488844, 5, 58], [1333, 2, 71], [1488844, 3, 76], [1333, 3, 77], [1488844, 3, 80], [1488844, 3, 81], [1488844, 3, 83], [1333, 3, 83], [695, 3, 83], [1333, 3, 97], [1333, 5, 107], [1488844, 3, 108], [1333, 3, 108], [2133, 3, 110], [1488844, 2, 111], [1333, 2, 111], [2133, 4, 111], [3292, 2, 111], [1488844, 3, 118], [1333, 2, 122], [1333, 1, 127], [1488844, 5, 143], [1333, 4, 143], [1856, 5, 143], [1333, 2, 148], [2133, 3, 148], [2133, 5, 152], [1488844, 3, 173], [1333, 2, 173], [1488844, 3, 175], [1333, 3, 175], [695, 2, 175], [3

user_id는 685,695,915,967,1333,1856,2133,2442,3292,1488844 총 10명으로 구성되어 있고 
movie_code는 1,3,4,5,8,17,18,26,28,30,44,48,52,55,57,58,71,76,77,80,81,83,97,107,108,
110,111,118,122,127,143,148,152,173,175,178,187,188,189,191,195,197,199,206,213,216,231,232,241 총 49개의 영화에 대한 레이팅 정보를 가진 배열을 만들겠습니다.

In [52]:
def array(list):
    a = np.zeros_like(list)
    for i in range(len(list)):
        element = list[i]
        if element[0] == 685 :
            a[i,0] = 0
        elif element[0] == 695:
            a[i,0] = 1
        elif element[0] == 915:
            a[i,0] = 2
        elif element[0] == 967:
            a[i,0] = 3
        elif element[0] == 1333:
            a[i,0] = 4
        elif element[0] == 1856:
            a[i,0] = 5
        elif element[0] == 2133:
            a[i,0] = 6
        elif element[0] == 2442:
            a[i,0] = 7
        elif element[0] == 3292:
            a[i,0] = 8
        elif element[0] == 1488844:
            a[i,0] = 9
# 유저를 배열 숫자에 맞게 바꿨습니다.            
    for i in range(len(list)):
        element = list[i]
        a[i,1] = int(element[1])
# rating를 배열 숫자에 맞게 바꿨습니다.                   
    for i in range(len(list)):
        element = list[i]
        if element[2] == 1 :
            a[i,2] = 0
        elif element[2] == 3:
            a[i,2] = 1
        elif element[2] == 4:
            a[i,2] = 2
        elif element[2] == 5:
            a[i,2] = 3
        elif element[2] == 8:
            a[i,2] = 4
        elif element[2] == 17:
            a[i,2] = 5
        elif element[2] == 18:
            a[i,2] = 6
        elif element[2] == 26:
            a[i,2] = 7
        elif element[2] == 28:
            a[i,2] = 8
        elif element[2] == 30:
            a[i,2] = 9
        elif element[2] == 44:
            a[i,2] = 10
        elif element[2] == 48:
            a[i,2] = 11
        elif element[2] == 52:
            a[i,2] = 12
        elif element[2] == 55:
            a[i,2] = 13
        elif element[2] == 57:
            a[i,2] = 14
        elif element[2] == 58:
            a[i,2] = 15
        elif element[2] == 71:
            a[i,2] = 16
        elif element[2] == 76:
            a[i,2] = 17
        elif element[2] == 77:
            a[i,2] = 18
        elif element[2] == 80:
            a[i,2] = 19
        elif element[2] == 81:
            a[i,2] = 20
        elif element[2] == 83:
            a[i,2] = 21
        elif element[2] == 97:
            a[i,2] = 22
        elif element[2] == 107:
            a[i,2] = 23
        elif element[2] == 108:
            a[i,2] = 24
        elif element[2] == 110:
            a[i,2] = 25
        elif element[2] == 111:
            a[i,2] = 26
        elif element[2] == 118:
            a[i,2] = 27
        elif element[2] == 122:
            a[i,2] = 28
        elif element[2] == 127:
            a[i,2] = 29
        elif element[2] == 143:
            a[i,2] = 30
        elif element[2] == 148:
            a[i,2] = 31
        elif element[2] == 152:
            a[i,2] = 32
        elif element[2] == 173:
            a[i,2] = 33
        elif element[2] == 175:
            a[i,2] = 34
        elif element[2] == 178:
            a[i,2] = 35
        elif element[2] == 187:
            a[i,2] = 36
        elif element[2] == 188:
            a[i,2] = 37
        elif element[2] == 189:
            a[i,2] = 38
        elif element[2] == 191:
            a[i,2] = 39
        elif element[2] == 195:
            a[i,2] = 40
        elif element[2] == 197:
            a[i,2] = 41
        elif element[2] == 199:
            a[i,2] = 42
        elif element[2] == 206:
            a[i,2] = 43
        elif element[2] == 213:
            a[i,2] = 44
        elif element[2] == 216:
            a[i,2] = 45
        elif element[2] == 231:
            a[i,2] = 46
        elif element[2] == 232:
            a[i,2] = 47
        elif element[2] == 241:
            a[i,2] = 48       
    return a
# movie code를 배열 숫자에 맞게 바꿨습니다.                   
b = array(list)
print(b)

[[ 9  3  0]
 [ 7  3  0]
 [ 2  5  0]
 [ 4  4  1]
 [ 3  1  2]
 [ 0  3  3]
 [ 9  4  4]
 [ 4  3  4]
 [ 6  2  4]
 [ 1  1  4]
 [ 8  4  4]
 [ 5  5  4]
 [ 9  2  5]
 [ 6  2  5]
 [ 4  4  6]
 [ 4  3  7]
 [ 4  2  8]
 [ 6  3  8]
 [ 9  3  9]
 [ 7  3  9]
 [ 4  3  9]
 [ 6  3  9]
 [ 8  4  9]
 [ 5  5  9]
 [ 9  3 10]
 [ 4  3 10]
 [ 6  3 11]
 [ 4  3 12]
 [ 8  4 12]
 [ 4  2 13]
 [ 4  4 14]
 [ 9  5 15]
 [ 4  2 16]
 [ 9  3 17]
 [ 4  3 18]
 [ 9  3 19]
 [ 9  3 20]
 [ 9  3 21]
 [ 4  3 21]
 [ 1  3 21]
 [ 4  3 22]
 [ 4  5 23]
 [ 9  3 24]
 [ 4  3 24]
 [ 6  3 25]
 [ 9  2 26]
 [ 4  2 26]
 [ 6  4 26]
 [ 8  2 26]
 [ 9  3 27]
 [ 4  2 28]
 [ 4  1 29]
 [ 9  5 30]
 [ 4  4 30]
 [ 5  5 30]
 [ 4  2 31]
 [ 6  3 31]
 [ 6  5 32]
 [ 9  3 33]
 [ 4  2 33]
 [ 9  3 34]
 [ 4  3 34]
 [ 1  2 34]
 [ 8  5 34]
 [ 4  3 35]
 [ 9  2 36]
 [ 4  3 36]
 [ 8  5 36]
 [ 7  3 37]
 [ 9  2 38]
 [ 9  5 39]
 [ 7  4 39]
 [ 4  1 39]
 [ 8  5 39]
 [ 9  4 40]
 [ 9  3 41]
 [ 4  2 41]
 [ 9  3 42]
 [ 4  3 42]
 [ 1  4 42]
 [ 4  3 43]
 [ 4  3 44]
 [ 9  3 45]
 [ 6

In [53]:
list_complete = np.zeros((10,49))
for i in range(len(b)):
    element = b[i]
    user = element[0]
    rating = element[1]
    moviecode = element[2]
    list_complete[user, moviecode] = rating
    
print(list_complete)
#유저별로 각 영화 코드에 맞게 rating을 넣었습니다.

[[0. 0. 0. 3. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 3. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 2. 0. 0. 0. 0. 0. 0. 0. 4. 0. 0. 0. 0. 0.
  4.]
 [5. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 4. 0. 0. 3. 0. 4. 3. 2. 3. 3. 0. 3. 2. 4. 0. 2. 0. 3. 0. 0. 3. 3. 5.
  3. 0. 2. 0. 2. 1. 4. 2. 0. 2. 3. 3. 3. 0. 0. 1. 0. 2. 3. 3. 3. 0. 3. 1.
  3.]
 [0. 0. 0. 0. 5. 0. 0. 0. 0. 5. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 5. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 2. 2. 0. 0. 3. 3. 0. 3. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  

In [54]:
# 알고리즘이 적용되는지 확인하는 예시입니다.
u = (4,1,1,4) 
v = (2,0,4,5)
A = np.array([[4,1,1,4],[0,4,2,0],[2,0,4,5],[1,4,0,1]])

In [55]:
def EUC(u, v):
    A =  np.sum(np.square(u - v))
    B = np.sqrt(A)
    return B
#두 리스트에 대한 유클리드 거리입니다.

def EUC_array(a):
    number_of_user = np.size(a, axis = 0)
    N = np.full((number_of_user, number_of_user), 0.0)
    #배열 a의 크기에 맞게 빈 배열을 만듭니다.
    for u in range(0, number_of_user):
        for v in range(u, number_of_user):
            A =  np.sum(np.square(a[u, ] - a[v, ]))
            N[v, u] = np.sqrt(A)
            N[u, v] = N[v, u]
    return N
#하나의 배열에 대한 유클리드 거리입니다.

In [56]:
def JAC(u, v):
    U = np.array(u > 0,dtype = np.int)
    V = np.array(v > 0, dtype = np.int)
    N = U + V
    inter = np.sum(np.array(N > 1, dtype = np.int)) # 배열의 교집합 부분입니다. 
    union = np.sum(np.array(N > 0, dtype = np.int)) # 배열의 합잡합 부분입니다.
    return inter/union
#두 리스트에 대한 JAC를 구하는 알고리즘입니다.

def JAC_array(a):
    number_of_user = np.size(a, axis = 0)
    N = np.full((number_of_user, number_of_user), 0.0)
    #배열 a의 크기에 맞게 빈 배열을 만듭니다.
    for u in range(0, number_of_user):
        for v in range(0, number_of_user):
            m = JAC(a[u, ],a[v, ])
            print(m)
            N[u, v] = m
            N[v,u] = N[u, v]
    return N
#하나의 배열에 대한 AC를 구하는 알고리즘입니다.

In [57]:
def MSD(u, v):
    U = np.where(u == 0, np.nan, u)
    V = np.where(v == 0, np.nan, v)
    sum = np.square(U - V)
    sum = sum[~np.isnan(sum)]
    
    size = np.size(sum, axis = 0)
    
    N = np.sum(sum)/size
    return N
#두 리스트에 대한 MSD를 구하는 알고리즘입니다.

def MSD_array(a):
    number_of_user = np.size(a, axis = 0)
    N = np.full((number_of_user, number_of_user), 0.0)
    #배열 a의 크기에 맞게 빈 배열을 만듭니다.
    for u in range(0, number_of_user):
        for v in range(0, number_of_user):
            m = MSD(a[u, ],a[v, ])
            N[u,v] = m
            N[v,u] = N[u, v]
    return N
#하나의 배열에 대한 MSD를 구하는 알고리즘입니다.


In [58]:
def JMSD(u, v, max):
    return JAC(u, v)* (1 - (MSD(u/max, v/max)))
#두 리스트에 대한 JMSD를 구하는 알고리즘입니다.

def JMSD(a, max):
    return JAC(a) * (1 - (MSD(a/max)))
#하나의 배열에 대한 JMSD를 구하는 알고리즘입니다.

In [59]:
def COS(u,v):
    return np.dot(u,v)/(np.linalg.norm(u) * np.linalg.norm(v))
#두 리스트에 대한 COS를 구하는 알고리즘입니다.

def COS_array(a):
    number_of_user = np.size(a, axis = 0)
    N = np.full((number_of_user, number_of_user), 0.0)
    #배열 a의 크기에 맞게 빈 배열을 만듭니다.
    for u in range(0, number_of_user):
        for v in range(0, number_of_user):
            m = COS(a[u, ],a[v, ])
            N[u,v] = m
            N[v,u] = N[u, v]
    return N
#하나의 배열에 대한 COS를 구하는 알고리즘입니다.

In [60]:
def COS_zero(u,v):
    zero_u = np.where(u== 0)
    zero_v = np.where(v ==0)
    zero = np.concatenate((zero_u, zero_v),axis = None)
    
    U = np.delete(u, zero)
    V = np.delete(v, zero)
    return np.dot(U, V)/(np.linalg.norm(U) * np.linalg.norm(V))
#두 리스트(NULL 부분 제외)에 대한 COS를 구하는 알고리즘입니다.

def COS_zero_array(a):
    number_of_user = np.size(a, axis = 0)
    N = np.full((number_of_user, number_of_user), 0.0)
    #배열 a의 크기에 맞게 빈 배열을 만듭니다.
    for u in range(0, number_of_user):
        for v in range(0, number_of_user):
            m = COS_zero(a[u, ],a[v, ])
            N[u,v] = m
            N[v,u] = N[u, v]
    return N
#하나의 배열(NULL 부분 제외)에 대한 COS를 구하는 알고리즘입니다.

In [61]:
def PCC(u, v):
    U_mean = np.nanmean(np.where(u!=0,np.nan))
    V_mean = np.nanmean(np.where(v!=0,np.nan))
    
    zero_u = np.where(u == 0)
    zero_v = np.where(v == 0)
    zero = np.concatenate((zero_u, zero_v), axis =None)
    
    U = np.delete(u, zero_u)
    V = np.delete(v, zero_v)
    U = U - U_mean
    V = V - V_mean
    
    return np.dot(U, V)/(np.linalg.norm(U) * np.linalg.norm(V))
#두 리스트(NULL 부분 제외)에 대한 PCC를 구하는 알고리즘입니다.

def PCC_array(a):
    number_of_user = np.size(a, axis = 0)
    N = np.full((number_of_user, number_of_user), 0.0)
    #배열 a의 크기에 맞게 빈 배열을 만듭니다.
    mean = np.nanmean(where(a!=0, np.nan), axis=1)
    
    for u in range(0, number_of_user):
        for v in range(0, number_of_user):
            zero_u = np.where(a[u, ] == 0)
            zero_v = np.where(a[v, ] == 0)
            zero = np.concatenate((zero_u, zero_v), axis =None)
      
            U = np.delete(a[u, ], zero_u)
            V = np.delete(a[v, ], zero_v)
            U = U - mean[u]
            V = V - mean[v]
            
            Inner = np.dot(U,V)
            N[u, v] = Inner/(np.linalg.norm(U) * np.linalg.norm(V))
            N[v,u] = N[u, v]
    return N
#하나의 배열(NULL 부분 제외)에 대한 PCC를 구하는 알고리즘입니다.

In [62]:
def CPCC(u, v):
    U_median = np.nanmedian(np.where(u!=0,u,np.nan))
    V_median = np.nanmedian(np.where(v!=0,v,np.nan))
    
    zero_u = np.where(u == 0)
    zero_v = np.where(v == 0)
    zero = np.concatenate((zero_u, zero_v), axis =None)
    
    U = np.delete(u, zero)
    V = np.delete(v, zero)
    U = U - U_median
    V = V - V_median
    
    return np.dot(U, V)/(np.linalg.norm(U) * np.linalg.norm(V))
#두 리스트(NULL 부분 제외)에 대한 CPCC를 구하는 알고리즘입니다.
# * 평균이 아니라 중간값을 사용합니다.

def CPCC_array(a):
    number_of_user = np.size(a, axis = 0)
    N = np.full((number_of_user, number_of_user), 0.0)
    #배열 a의 크기에 맞게 빈 배열을 만듭니다.
    median = np.nanmedian(np.where(a!=0, a, np.nan), axis=1)
    
    for u in range(0, number_of_user):
        for v in range(0, number_of_user):
            zero_u = np.where(a[u, ] == 0)
            zero_v = np.where(a[v, ] == 0)
            zero = np.concatenate((zero_u, zero_v), axis =None)
      
            U = np.delete(a[u, ], zero_u)
            V = np.delete(a[v, ], zero_v)
            U = U - median[u]
            V = V - median[v]
            
            Inner = np.dot(U,V)
            N[u, v] = Inner/(np.linalg.norm(U) * np.linalg.norm(V))
            N[v,u] = N[u, v]
            N[np.isnan(N)] = -1
    return N    