In [1]:
import pandas as pd
import surprise
import numpy as np

위에 있는 패키지는 Similarity를 구하기 위해 필요한 패키지들입니다.

In [154]:
import os.path
import csv

list = []
movie_code = 0
search = ":"

with open('data/combined_data_1.txt','r') as textfile:
    for row in textfile:
        row_split = row.split()
        for element in row_split:
            element_split = element.split(',')
            check = element_split[0]
            result = check.find(search)
            check = check.replace(":","")
            if result == -1:
                element_split.append(movie_code)
                list.append(element_split)
            else:
                movie_code = check

combined_data_1.txt 데이터가 

movie code:
    
    user_id , rating, timestamp 순으로 되어있어서 

user_id , rating, timestamp, movie code 순으로 배열을 만들었습니다.

In [3]:
import csv

csvfile = open("C:/Users/Minwook/Documents/Netflix_data/data/test.csv","w",newline="")

csvwriter = csv.writer(csvfile)
for row in list:
    csvwriter.writerow(row)

csvfile.close()

데이터 구성은 각 영화에 해당되는 태그 마다 
user_id , rating, timestamp, movie code로 구성되어 있습니다.

Neflix data가 너무 큰 관계로 범위를 한정시켰습니다.
Neflix data가 user_id , rating, timestamp, movie code오 이루어진 textfile이 4개로
나누어져 있는데, 그 중에서 combined_data_1.txt 를 이용해 구현해보았습니다. 수업을 들으면서 더 많은 양의 데이터를 처리할 수 있도록 노력하겠습니다!

In [2]:
import openpyxl
 
# 엑셀파일 열기
workbook = openpyxl.load_workbook('data/test_combine_1.xlsx')
 
# 현재 Active Sheet 얻기
workbook_value = workbook.active
element = [] 
list_data = []

for r in workbook_value.rows:
    user_id = r[0].value   
    rating = r[1].value
    timestamp = r[2].value
    movie_code = r[3].value
    # 각 행별로 원소를 지정했습니다.
    element = element + [user_id, rating , movie_code] 
    list_data.append(element)
    element = []
# csv 파일을 불러드려서 User_id, rating, movie_code 순으로 되있는 리스트를 원소로 
# 갖는 배열을 만듭니다.
print(list_data[0:5])

[[1488844, 3, 1], [822109, 5, 1], [885013, 4, 1], [30878, 4, 1], [823519, 3, 1]]


* 처음으론 데이터의 일부분만 이용해서 전처리를 진행하겠습니다.
* 이 부분은 조별 발표할 때, 이용했던 코드여서 남겨두겠습니다!
* (아래 전체 데이터 전처리한 부분도 있습니다!)


user_id는 
685,695,915,967,1333,1856,2133,2442,3292,1488844 총 10명으로 구성되어 있고 

movie_code는
1,3,4,5,8,17,18,26,28,30,44,48,52,55,57,58,71,76,77,80,81,83,97,107,108,110,111,118,122,127,
143,148,152,173,175,178,187,188,189,191,195,197,199,206,213,216,231,232,241 
총 49개의 영화에 대한 레이팅 정보를 가진 배열을 만들겠습니다.

In [9]:
def array(list):
    a = np.zeros_like(list)
    for i in range(len(list)):
        element = list[i]
        if element[0] == 685 :
            a[i,0] = 0
        elif element[0] == 695:
            a[i,0] = 1
        elif element[0] == 915:
            a[i,0] = 2
        elif element[0] == 967:
            a[i,0] = 3
        elif element[0] == 1333:
            a[i,0] = 4
        elif element[0] == 1856:
            a[i,0] = 5
        elif element[0] == 2133:
            a[i,0] = 6
        elif element[0] == 2442:
            a[i,0] = 7
        elif element[0] == 3292:
            a[i,0] = 8
        elif element[0] == 1488844:
            a[i,0] = 9
# 유저를 배열 숫자에 맞게 바꿨습니다.            
    for i in range(len(list)):
        element = list[i]
        a[i,1] = int(element[1])
# rating를 배열 숫자에 맞게 바꿨습니다.                   
    for i in range(len(list)):
        element = list[i]
        if element[2] == 1 :
            a[i,2] = 0
        elif element[2] == 3:
            a[i,2] = 1
        elif element[2] == 4:
            a[i,2] = 2
        elif element[2] == 5:
            a[i,2] = 3
        elif element[2] == 8:
            a[i,2] = 4
        elif element[2] == 17:
            a[i,2] = 5
        elif element[2] == 18:
            a[i,2] = 6
        elif element[2] == 26:
            a[i,2] = 7
        elif element[2] == 28:
            a[i,2] = 8
        elif element[2] == 30:
            a[i,2] = 9
        elif element[2] == 44:
            a[i,2] = 10
        elif element[2] == 48:
            a[i,2] = 11
        elif element[2] == 52:
            a[i,2] = 12
        elif element[2] == 55:
            a[i,2] = 13
        elif element[2] == 57:
            a[i,2] = 14
        elif element[2] == 58:
            a[i,2] = 15
        elif element[2] == 71:
            a[i,2] = 16
        elif element[2] == 76:
            a[i,2] = 17
        elif element[2] == 77:
            a[i,2] = 18
        elif element[2] == 80:
            a[i,2] = 19
        elif element[2] == 81:
            a[i,2] = 20
        elif element[2] == 83:
            a[i,2] = 21
        elif element[2] == 97:
            a[i,2] = 22
        elif element[2] == 107:
            a[i,2] = 23
        elif element[2] == 108:
            a[i,2] = 24
        elif element[2] == 110:
            a[i,2] = 25
        elif element[2] == 111:
            a[i,2] = 26
        elif element[2] == 118:
            a[i,2] = 27
        elif element[2] == 122:
            a[i,2] = 28
        elif element[2] == 127:
            a[i,2] = 29
        elif element[2] == 143:
            a[i,2] = 30
        elif element[2] == 148:
            a[i,2] = 31
        elif element[2] == 152:
            a[i,2] = 32
        elif element[2] == 173:
            a[i,2] = 33
        elif element[2] == 175:
            a[i,2] = 34
        elif element[2] == 178:
            a[i,2] = 35
        elif element[2] == 187:
            a[i,2] = 36
        elif element[2] == 188:
            a[i,2] = 37
        elif element[2] == 189:
            a[i,2] = 38
        elif element[2] == 191:
            a[i,2] = 39
        elif element[2] == 195:
            a[i,2] = 40
        elif element[2] == 197:
            a[i,2] = 41
        elif element[2] == 199:
            a[i,2] = 42
        elif element[2] == 206:
            a[i,2] = 43
        elif element[2] == 213:
            a[i,2] = 44
        elif element[2] == 216:
            a[i,2] = 45
        elif element[2] == 231:
            a[i,2] = 46
        elif element[2] == 232:
            a[i,2] = 47
        elif element[2] == 241:
            a[i,2] = 48       
    return a
# movie code를 배열 숫자에 맞게 바꿨습니다.                   
b = array(list)

print(b[0:5])

# 리스트 b에 대한 데이터 전처리입니다.
list_complete = np.zeros((10,49))
for i in range(len(b)):
    element = b[i]
    user = element[0]
    rating = element[1]
    moviecode = element[2]
    list_complete[user, moviecode] = rating
    
print(list_complete[0:5])
#유저별로 각 영화 코드에 맞게 rating을 넣었습니다.

[[9 3 0]
 [7 3 0]
 [2 5 0]
 [4 4 1]
 [3 1 2]]


* 다음으로 전체 데이터를 전처리해보도록 하겠습니다.


combined_data_1.txt를 test.csv로 바꾸어서 1048576개의 데이터를 
2649429(CustomerID의 범위는 1 to 2649429) x 241(combined_data_1.txt 안에 있는 데이터 코드가 1 to 241)의 행렬로 만들고 CustomerID는 존재하나 아무 rating이 존재하지 않는 열을 정리 하도록 하겠습니다.

In [18]:
list_complete = np.zeros((2649430,242))
#User_id는 1 to 2649429 이고 movie_code는 1 to 241까지입니다.
for i in range(0,1048576):
    element = list_data[i]
    user = element[0]
    rating = element[1]
    moviecode = element[2]
    list_complete[user, moviecode] = rating
    
#유저별로 각 영화 코드에 맞게 rating을 넣었습니다.
#하지만 Bool값이 많으므로 전처리를 해줍니다.
list_check_userid = []
list_check_moviecode = []
element = []
for i in range(0, 1048576):
    element = list_data[i]
    list_check_userid.append(element[0])
    list_check_moviecode.append(element[2])

list_check_userid = np.unique(list_check_userid)
list_check_moviecode = np.unique(list_check_moviecode)
#실제 rating값이 있는 userid와 moviecode를 정렬해줍니다.

element = []
list_completes = []
for i in range(0,287457):
    a = list_check_userid[i]
    element = list_complete[a]
    list_completes.append(element)
print(list_completes[0])
#그 중에서 rating이 없는 userid행을 지워줍니다.
a = list_completes[0:20]
a = np.array(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 3. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 3. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 4. 0. 5. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 2.
 0. 0. 0. 0. 0. 3. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0.]


In [4]:
def EUC(u, v):
    A =  np.sum(np.square(u - v))
    B = np.sqrt(A)
    return B
#두 리스트에 대한 유클리드 거리입니다.

def EUC_array(a):
    number_of_user = np.size(a, axis = 0)
    N = np.full((number_of_user, number_of_user), 0.0)
    #배열 a의 크기에 맞게 빈 배열을 만듭니다.
    for u in range(0, number_of_user):
        for v in range(u, number_of_user):
            A =  np.sum(np.square(a[u,] - a[v,]))
            N[v, u] = np.sqrt(A)
            N[u, v] = N[v, u]
    return N
#하나의 배열에 대한 유클리드 거리입니다.

In [5]:
def JAC(u, v):
    U = np.array(u > 0,dtype = np.int)
    V = np.array(v > 0, dtype = np.int)
    N = U + V
    inter = np.sum(np.array(N > 1, dtype = np.int)) # 배열의 교집합 부분입니다. 
    union = np.sum(np.array(N > 0, dtype = np.int)) # 배열의 합잡합 부분입니다.
    return inter/union
#두 리스트에 대한 JAC를 구하는 알고리즘입니다.

def JAC_array(a):
    number_of_user = np.size(a, axis = 0)
    N = np.full((number_of_user, number_of_user), 0.0)
    #배열 a의 크기에 맞게 빈 배열을 만듭니다.
    for u in range(0, number_of_user):
        for v in range(0, number_of_user):
            m = JAC(a[u, ],a[v, ])
            N[u, v] = m
            N[v,u] = N[u, v]
    return N
#하나의 배열에 대한 AC를 구하는 알고리즘입니다.

In [6]:
def MSD(u, v):
    U = np.where(u == 0, np.nan, u)
    V = np.where(v == 0, np.nan, v)
    sum = np.square(U - V)
    sum = sum[~np.isnan(sum)]
    
    size = np.size(sum, axis = 0)
    
    N = np.sum(sum)/size
    return N
#두 리스트에 대한 MSD를 구하는 알고리즘입니다.

def MSD_array(a):
    number_of_user = np.size(a, axis = 0)
    N = np.full((number_of_user, number_of_user), 0.0)
    #배열 a의 크기에 맞게 빈 배열을 만듭니다.
    for u in range(0, number_of_user):
        for v in range(0, number_of_user):
            m = MSD(a[u,],a[v,])
            N[u,v] = m
            N[v,u] = N[u, v]
    return N
#하나의 배열에 대한 MSD를 구하는 알고리즘입니다.


In [7]:
def JMSD(u, v, max):
    return JAC(u, v)* (1 - (MSD(u/max, v/max)))
#두 리스트에 대한 JMSD를 구하는 알고리즘입니다.

def JMSD(a, max):
    return JAC(a) * (1 - (MSD(a/max)))
#하나의 배열에 대한 JMSD를 구하는 알고리즘입니다.

In [8]:
def COS(u,v):
    return np.dot(u,v)/(np.linalg.norm(u) * np.linalg.norm(v))
#두 리스트에 대한 COS를 구하는 알고리즘입니다.

def COS_array(a):
    number_of_user = np.size(a, axis = 0)
    N = np.full((number_of_user, number_of_user), 0.0)
    #배열 a의 크기에 맞게 빈 배열을 만듭니다.
    for u in range(0, number_of_user):
        for v in range(0, number_of_user):
            m = COS(a[u, ],a[v, ])
            N[u,v] = m
            N[v,u] = N[u, v]
    return N
#하나의 배열에 대한 COS를 구하는 알고리즘입니다.

In [9]:
def COS_zero(u,v):
    zero_u = np.where(u== 0)
    zero_v = np.where(v ==0)
    zero = np.concatenate((zero_u, zero_v),axis = None)
    
    U = np.delete(u, zero)
    V = np.delete(v, zero)
    return np.dot(U, V)/(np.linalg.norm(U) * np.linalg.norm(V))
#두 리스트(NULL 부분 제외)에 대한 COS를 구하는 알고리즘입니다.

def COS_zero_array(a):
    number_of_user = np.size(a, axis = 0)
    N = np.full((number_of_user, number_of_user), 0.0)
    #배열 a의 크기에 맞게 빈 배열을 만듭니다.
    for u in range(0, number_of_user):
        for v in range(0, number_of_user):
            m = COS_zero(a[u, ],a[v, ])
            N[u,v] = m
            N[v,u] = N[u, v]
    return N
#하나의 배열(NULL 부분 제외)에 대한 COS를 구하는 알고리즘입니다.

In [10]:
def PCC(u, v):
    U_mean = np.nanmean(np.where(u!=0,np.nan))
    V_mean = np.nanmean(np.where(v!=0,np.nan))
    
    zero_u = np.where(u == 0)
    zero_v = np.where(v == 0)
    zero = np.concatenate((zero_u, zero_v), axis =None)
    
    U = np.delete(u, zero_u)
    V = np.delete(v, zero_v)
    U = U - U_mean
    V = V - V_mean
    
    return np.dot(U, V)/(np.linalg.norm(U) * np.linalg.norm(V))
#두 리스트(NULL 부분 제외)에 대한 PCC를 구하는 알고리즘입니다.

def PCC_array(a):
    number_of_user = np.size(a, axis = 0)
    N = np.full((number_of_user, number_of_user), 0.0)
    #배열 a의 크기에 맞게 빈 배열을 만듭니다.
    mean = np.nanmean(np.where(a!=0, a, np.nan), axis=1)
    
    for u in range(0, number_of_user):
        for v in range(0, number_of_user):
            zero_u = np.where(a[u, ] == 0)
            zero_v = np.where(a[v, ] == 0)
            zero = np.concatenate((zero_u, zero_v), axis =None)
      
            U = np.delete(a[u, ], zero)
            V = np.delete(a[v, ], zero)
            U = U - mean[u]
            V = V - mean[v]
            
            Inner = np.dot(U,V)
            N[u, v] = Inner/(np.linalg.norm(U) * np.linalg.norm(V))
            N[v,u] = N[u, v]
    return N
#하나의 배열(NULL 부분 제외)에 대한 PCC를 구하는 알고리즘입니다.

In [11]:
def CPCC(u, v):
    U_median = np.nanmedian(np.where(u!=0,u,np.nan))
    V_median = np.nanmedian(np.where(v!=0,v,np.nan))
    
    zero_u = np.where(u == 0)
    zero_v = np.where(v == 0)
    zero = np.concatenate((zero_u, zero_v), axis =None)
    
    U = np.delete(u, zero)
    V = np.delete(v, zero)
    U = U - U_median
    V = V - V_median
    
    return np.dot(U, V)/(np.linalg.norm(U) * np.linalg.norm(V))
#두 리스트(NULL 부분 제외)에 대한 CPCC를 구하는 알고리즘입니다.
# * 평균이 아니라 중간값을 사용합니다.

def CPCC_array(a):
    number_of_user = np.size(a, axis = 0)
    N = np.full((number_of_user, number_of_user), 0.0)
    #배열 a의 크기에 맞게 빈 배열을 만듭니다.
    median = np.nanmedian(np.where(a!=0, a, np.nan), axis=1)
    
    for u in range(0, number_of_user):
        for v in range(0, number_of_user):
            zero_u = np.where(a[u, ] == 0)
            zero_v = np.where(a[v, ] == 0)
            zero = np.concatenate((zero_u, zero_v), axis =None)
      
            U = np.delete(a[u, ], zero)
            V = np.delete(a[v, ], zero)
            U = U - median[u]
            V = V - median[v]
            
            Inner = np.dot(U,V)
            N[u, v] = Inner/(np.linalg.norm(U) * np.linalg.norm(V))
            N[v,u] = N[u, v]
            N[np.isnan(N)] = -1
    return N    

In [19]:
EUC_array(a)

array([[ 0.        , 11.13552873,  6.55743852,  9.        ,  8.        ,
         7.28010989,  8.54400375,  8.77496439,  8.24621125,  8.71779789,
         9.11043358,  8.        ,  8.06225775, 15.58845727,  9.        ,
         6.8556546 ,  8.        ,  9.38083152,  7.93725393,  7.48331477],
       [11.13552873,  0.        , 11.26942767, 12.52996409, 12.80624847,
        11.18033989, 11.        , 11.18033989, 11.3137085 , 12.32882801,
        10.90871211, 11.13552873, 11.87434209, 16.09347694, 12.52996409,
        11.09053651, 11.13552873, 12.16552506, 12.52996409, 11.83215957],
       [ 6.55743852, 11.26942767,  0.        ,  7.07106781,  5.        ,
         5.09901951,  5.83095189,  6.92820323,  6.40312424,  6.70820393,
         8.        ,  7.54983444,  6.4807407 , 13.85640646,  7.07106781,
         6.        ,  7.54983444,  6.40312424,  5.09901951,  6.40312424],
       [ 9.        , 12.52996409,  7.07106781,  0.        ,  5.        ,
         7.07106781,  6.4807407 ,  6.92820323,  

In [20]:
JAC_array(a)

array([[1.        , 0.3       , 0.5       , 0.        , 0.16666667,
        0.5       , 0.28571429, 0.22222222, 0.22222222, 0.        ,
        0.125     , 0.16666667, 0.14285714, 0.07692308, 0.        ,
        0.16666667, 0.16666667, 0.14285714, 0.16666667, 0.33333333],
       [0.3       , 1.        , 0.25      , 0.        , 0.        ,
        0.25      , 0.25      , 0.2       , 0.2       , 0.        ,
        0.25      , 0.14285714, 0.125     , 0.15384615, 0.        ,
        0.14285714, 0.14285714, 0.125     , 0.        , 0.125     ],
       [0.5       , 0.25      , 1.        , 0.        , 0.33333333,
        0.5       , 0.2       , 0.14285714, 0.33333333, 0.        ,
        0.2       , 0.        , 0.25      , 0.1       , 0.        ,
        0.33333333, 0.        , 0.25      , 0.33333333, 0.25      ],
       [0.        , 0.        , 0.        , 1.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0

In [21]:
COS_array(a)

array([[1.        , 0.46499055, 0.6441839 , 0.        , 0.35355339,
        0.55215763, 0.32824398, 0.32081183, 0.49391458, 0.        ,
        0.27607882, 0.35355339, 0.32686023, 0.08527409, 0.        ,
        0.58925565, 0.35355339, 0.16666667, 0.35355339, 0.5       ],
       [0.46499055, 1.        , 0.39795953, 0.        , 0.        ,
        0.41079693, 0.42927286, 0.40803605, 0.42801319, 0.        ,
        0.44930915, 0.41099747, 0.22798038, 0.23790986, 0.        ,
        0.41099747, 0.41099747, 0.23249528, 0.        , 0.2906191 ],
       [0.6441839 , 0.39795953, 1.        , 0.        , 0.62469505,
        0.68292683, 0.54372725, 0.40012506, 0.61485672, 0.        ,
        0.2195122 , 0.        , 0.25988885, 0.22600674, 0.        ,
        0.46852129, 0.        , 0.4417261 , 0.62469505, 0.4417261 ],
       [0.        , 0.        , 0.        , 1.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0

In [22]:
PCC_array(a)

C:\Users\Minwook\Anaconda3\lib\site-packages\ipykernel_launcher.py:35: RuntimeWarning: invalid value encountered in double_scalars


array([[ 1.        ,  0.74095857, -0.94491118,         nan,         nan,
         0.57735027, -0.7592566 , -0.99944491,  0.45985425,         nan,
        -1.        ,         nan, -1.        , -1.        ,         nan,
                nan,         nan,         nan,         nan,         nan],
       [ 0.74095857,  1.        , -0.89442719,         nan,         nan,
         0.98386991, -0.98386991, -0.60438648,  0.22337616,         nan,
        -0.31622777,         nan, -1.        , -1.        ,         nan,
                nan,         nan,         nan,         nan,         nan],
       [-0.94491118, -0.89442719,  1.        ,         nan,         nan,
        -0.31622777,  1.        ,  1.        , -0.63570725,         nan,
         1.        ,         nan,  1.        ,  1.        ,         nan,
                nan,         nan,         nan,         nan,         nan],
       [        nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,  

In [23]:
CPCC_array(a)

C:\Users\Minwook\Anaconda3\lib\site-packages\ipykernel_launcher.py:36: RuntimeWarning: invalid value encountered in double_scalars


array([[ 1.        ,  0.4472136 , -0.89442719, -1.        , -1.        ,
         1.        , -1.        , -1.        ,  0.89442719, -1.        ,
        -1.        , -1.        , -1.        , -1.        , -1.        ,
        -1.        , -1.        , -1.        , -1.        , -1.        ],
       [ 0.4472136 ,  1.        ,  0.        , -1.        , -1.        ,
         1.        , -1.        , -1.        ,  0.        , -1.        ,
        -1.        , -1.        , -1.        , -1.        , -1.        ,
        -1.        , -1.        , -1.        , -1.        , -1.        ],
       [-0.89442719,  0.        ,  1.        , -1.        , -1.        ,
        -1.        , -1.        , -1.        , -1.        , -1.        ,
         1.        , -1.        ,  1.        , -1.        , -1.        ,
        -1.        , -1.        , -1.        , -1.        , -1.        ],
       [-1.        , -1.        , -1.        , -1.        , -1.        ,
        -1.        , -1.        , -1.        , -